[pytest]
addopts = -vs --alluredir=./temps --clean-alluredir
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = .venv __pycache__ .pytest_cache api-test-framework api_test_framework
log_cli = true
log_cli_level = INFO
log_cli_format = [%(levelname)s] %(message)s